name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/PocoF1-Resources/android_kernel_xiaomi_sdm845
          kernel-branch: 16.0-KSU-Next
          config: sdm845_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 13
          aosp-clang-version: r383902
