name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/PocoF1-Resources/android_kernel_xiaomi_sdm845
          kernel-branch: 16.0-KSU-Next
          config: sdm845_defconfig
          arch: arm64
          
          aosp-clang: false 
          other-clang-url: 'https://github.com/kdrag0n/proton-clang'
          other-clang-branch: 'master'

          # --- Feature Configuration ---
          ksu: true # Enable KernelSU, as per the branch name
          anykernel3: true # Package the result into a flashable zip

          # --- Build & Release Configuration ---
          # This command adds the custom name to your kernel version string
          extra-cmd: 'LOCALVERSION="-Etude-Op.13-No.2"' 
          release: true # Automatically create a release with the zip
          access-token: ${{ secrets.GITHUB_TOKEN }} # Token to allow releasing
