name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-latest # Use the latest available runner
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/PocoF1-Resources/android_kernel_xiaomi_sdm845
          kernel-branch: 16.0-KSU-Next
          config: sdm845_defconfig
          arch: arm64
          
          # --- Toolchain Configuration ---
          # We are now using the specific AOSP Clang version
          aosp-gcc: true
          aosp-clang: true 
          aosp-clang-version: 'r487747c' # This is the specific revision for Clang 17.0.2

          # --- Feature Configuration ---
          ksu: false
          anykernel3: true

          # --- Build & Release Configuration ---
          extra-cmd: 'LOCALVERSION="-Etude-Op.13-No.2"'
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
